all:
	@go run ./cmd/kronosd/main.go
test-all:
	@go test ./...
test-unit:
	@go test --tags=unit -v ./...
test-integration:
	@go test --tags=integration -v ./...
cover:
	@go test ./... -v -cover
lint:
	@golint ./...
